# Generated by Django 4.1.13 on 2026-03-04 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contact',
            table='contacts',
        ),
    ]
