# Generated by Django 4.1.13 on 2026-03-27 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0009_servicereview_updated_at_and_more'),
        ('products', '0004_order_estimated_delivery_date_order_tax_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='appointments.appointment'),
        ),
    ]
