# Generated by Django 4.1.13 on 2026-03-04 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_add_advance_payment_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='service',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=models.CharField(help_text='Unique key that matches URL and appointment type.', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='servicereview',
            name='service',
            field=models.CharField(max_length=50),
        ),
    ]
