# Generated by Django 4.1.13 on 2026-03-04 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_alter_appointment_service_alter_service_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='service',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=models.CharField(help_text='Unique key that matches URL and appointment type (e.g., puppy-first-bath).', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='servicereview',
            name='service',
            field=models.CharField(max_length=100),
        ),
    ]
