# Generated by Django 4.1.13 on 2026-04-01 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0009_servicereview_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicereview',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
