# Generated by Django 4.1.13 on 2026-04-12 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appointments', '0011_appointment_assigned_staff'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='service',
        #     name='name',
        #     field=models.CharField(max_length=100, unique=True),
        # ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pet_type', models.CharField(help_text='e.g. Dog, Cat, Rabbit', max_length=50)),
                ('breed', models.CharField(blank=True, max_length=100)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('medical_notes', models.TextField(blank=True, help_text='Known allergies, health issues, or medicines.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pets',
                'ordering': ['name'],
                'unique_together': {('user', 'name')},
            },
        ),
    ]
