# Generated by Django 4.2.7 on 2025-11-25 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(default='0000000000', max_length=15, unique=True),
        ),
    ]
