"""
Django settings for himalayan_pet_studio project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
import smtplib



BASE_DIR = Path(__file__).resolve().parent.parent






SECRET_KEY = 'django-insecure-himalayan-pet-studio-secret-key-change-in-production'


DEBUG = True

ALLOWED_HOSTS = ['*']




INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts',
    'appointments',
    'products',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'himalayan_pet_studio.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR.parent, 'frontend', 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'accounts.context_processors.unread_contact_count',
                'accounts.context_processors.khalti_config',
                'products.context_processors.cart_count',
            ],
        },
    },
]

WSGI_APPLICATION = 'himalayan_pet_studio.wsgi.application'






DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'himalayan_pet_studio',
        'USER': 'root',
        'PASSWORD': '1234',  
        'HOST': '127.0.0.1',
        'PORT': '3306',
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        },
    }
}







AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]





LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kathmandu'

USE_I18N = True

USE_TZ = True





STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR.parent, 'frontend', 'static'),
]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')




DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


AUTH_USER_MODEL = 'accounts.User'


SESSION_ENGINE = 'django.contrib.sessions.backends.cached_db'  
SESSION_COOKIE_AGE = 600  
SESSION_SAVE_EVERY_REQUEST = True  
SESSION_EXPIRE_AT_BROWSER_CLOSE = True  
SESSION_COOKIE_NAME = 'himalayan_pet_sessionid'
SESSION_COOKIE_HTTPONLY = True  
SESSION_COOKIE_SECURE = False  
SESSION_COOKIE_SAMESITE = 'Lax'  


CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
    }
}


LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'user_dashboard'
LOGOUT_REDIRECT_URL = 'login'


KHALTI_PUBLIC_KEY = os.environ.get('KHALTI_PUBLIC_KEY', '87ebfe01e2f24a0091a8ef2831e96b91')
KHALTI_SECRET_KEY = os.environ.get('KHALTI_SECRET_KEY', 'ec1855a02a0d42ea95d3dc36b0cf0c39')
KHALTI_BASE_URL = "https://khalti.com/api/v2/" if KHALTI_SECRET_KEY.startswith('live_') else "https://a.khalti.com/api/v2/"



EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 465
EMAIL_USE_TLS = False
EMAIL_USE_SSL = True
EMAIL_HOST_USER = 'himalayanpetgrommingstudio12@gmail.com'  
EMAIL_HOST_PASSWORD = 'motbmwzdcuwgfxda'  
DEFAULT_FROM_EMAIL = 'himalayanpetgrommingstudio12@gmail.com'



_original_starttls = smtplib.SMTP.starttls
_original_ssl_init = smtplib.SMTP_SSL.__init__

def _fixed_starttls(self, *args, **kwargs):
    kwargs.pop('keyfile', None)
    kwargs.pop('certfile', None)
    return _original_starttls(self, *args, **kwargs)

def _fixed_ssl_init(self, *args, **kwargs):
    kwargs.pop('keyfile', None)
    kwargs.pop('certfile', None)
    return _original_ssl_init(self, *args, **kwargs)

smtplib.SMTP.starttls = _fixed_starttls  
smtplib.SMTP_SSL.__init__ = _fixed_ssl_init  